//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoP5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class asddsa
    {
        public int Espacio1 { get; set; }
        public string Espacio2 { get; set; }
        public string Espacio3 { get; set; }
        public string Espacio4 { get; set; }
    }
}
